services:
  smartuni.db:
    image: postgres
    container_name: smartuni.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartuni
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  smartuni.ollama:
    image: ollama/ollama:latest
    container_name: smartuni.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_API_URL=http://localhost:11434
    volumes:
      - ollama_data:/.ollama
  #    entrypoint: [ "/bin/sh", "-c" ]
  #    command: ollama serve &> /var/log/ollama.log & while ! curl -s http://localhost:11434 > /dev/null; do echo "Waiting for ollama service..." && sleep 2; done && ollama run llama2 &>> /var/log/ollama.log && tail -f /dev/null

  smartuni.api:
    container_name: smartuni.api
    build:
      context: .
      dockerfile: ./src/SmartUni.PublicApi/Dockerfile
    depends_on:
      - smartuni.db
      - smartuni.ollama
    ports:
      - "7142:7142"
    environment:
      - ASPNETCORE_HTTP_PORT=7142
      - ASPNETCORE_URLS=http://+:7142
      - ASPNETCORE_ENVIRONMENT=Development.docker
      - "ConnectionStrings:SmartUniDb=Server=smartuni.db;Port=5432;Database=smartuni;User Id=postgres;Password=postgres;Include Error Detail=true;"
  
  smartuni.seq:
    image: datalust/seq:latest
    container_name: smartuni.seq
    ports:
      - "5341:5341"
      - "8080:80"
    environment:
      - ACCEPT_EULA=Y
  
volumes:
  postgres_data:
  ollama_data: