name: SmartUni.Backend CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["9.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore --project ../../src/SmartUni.Backend/SmartUni.Backend.csproj
      - name: Build project
        run: dotnet build --no-restore --project ../../src/SmartUni.Backend/SmartUni.Backend.csproj
